<?php

namespace Pidev\homeBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * EvennementguestRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */


class EvennementguestRepository extends EntityRepository
{

}