<?php

namespace Pidev\homeBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ExperienceRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */


class ExperienceRepository extends EntityRepository
{

}