<?php

namespace Pidev\homeBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * genre_logementRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */


class genre_logementRepository extends EntityRepository
{

}