<?php

   namespace Pidev\homeBundle\Repository;

   use Doctrine\ORM\EntityRepository;

   /**
    * genreRepository
    *
    * this class was generated by the Doctrine ORM.Add your own custom
    * repository methods below.
    */
  class genreRepository extends EntityRepository
{

}