<?php

namespace Pidev\homeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * imageRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */
class imageRepository extends EntityRepository
{

}