<?php

namespace Pidev\homeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * type_logementRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */
class type_logementRepository extends EntityRepository
{

}