<?php

namespace Pidev\homeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * vieamicaleRepository
 *
 * this class was generated by the Doctrine ORM.Add your own custom
 * repository methods below.
 */
class vieamicaleRepository extends EntityRepository
{

}